@echo off
echo Building App...
call npm run build
echo Copying Setup Script...
copy OneClickSetup.bat dist\OneClickSetup.bat
echo Zipping...
powershell -Command "Compress-Archive -Path dist\* -DestinationPath LuckyBoba_Branded_Installer.zip -Force"
echo DONE!
